version: "3.6"

services:

    nginx:
        build: ./docker/nginx
        container_name: nginx
        working_dir: /srv
        restart: on-failure
        volumes:
            - ./symfony:/srv/symfony:cached
            - ./logs/nginx:/var/log/nginx:cached
        ports:
            - "8080:80"
        depends_on:
            - php-fpm

    php-fpm:
        build: ./docker/php-fpm
        container_name: php-fpm
        working_dir: /srv
        restart: on-failure
        volumes:
            - ./symfony:/srv/symfony:cached
            - ./logs/symfony:/srv/symfony/var/log:cached
        depends_on:
            - database

    database:
        image: mariadb:latest
        container_name: database
        working_dir: /srv
        restart: on-failure

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
            ELASTIC_PASSWORD: changeme
            discovery.type: single-node
        volumes:
            - ./docker/elk/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:cached
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            elk_stack:
                aliases:
                    - "elasticsearch"

    logstash:
        container_name: logstash
        build: ./docker/elk/logstash
        depends_on:
            - elasticsearch
        volumes:
            - ./logs/symfony:/srv/symfony/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk_stack

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.0
        depends_on:
            - elasticsearch
        volumes:
            - ./docker/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:cached
        networks:
            - elk_stack
        ports:
            - "81:5601"

networks:
    elk_stack: